apiVersion: 1

datasources:
  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: Loki
    access: proxy
    type: loki
    url: http://loki:3100
    editable: true
    
  - name: Tempo
    access: proxy
    type: tempo
    url: http://tempo:3200
    editable: true