apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapi.name }}
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app: {{ .Values.webapi.name }}
spec:
  replicas: {{ .Values.webapi.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.webapi.name }}
      app.kubernetes.io/name: {{ include "sample-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- include "sample-app.podAnnotations" .Values.webapi.name | nindent 8 }}
      labels:
        app: {{ .Values.webapi.name }}
        {{- include "sample-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sample-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.webapi.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.webapi.image.repository }}:{{ .Values.webapi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webapi.image.pullPolicy }}
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: {{ include "sample-app.fullname" . }}-config-map
          ports:
            - name: http
              containerPort: {{ .Values.webapi.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
