# Grafana
# ======================================================================================================================
grafana:
  enabled: true
  namespaceOverride: observability
  adminUser: admin
  adminPassword: admin
  testFramework:
    enabled: false
  serviceAccount:
    create: false
    name: dev-140891-observability
    annotations:
      iam.gke.io/gcp-service-account: dev-140891-observability@paul-soladoye.iam.gserviceaccount.com
  nodeSelector:
    node_pool: dev-140891-sb-pool
#    sandbox.gke.io/runtime: gvisor
  tolerations:
#    - key: sandbox.gke.io/runtime
#      value: gvisor
#      effect: NoSchedule'
  env:
    GF_AUTH_ANONYMOUS_ENABLED: true
    GF_LOG_LEVEL: debug
  service:
    port: 3000
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          access: proxy
          type: prometheus
          url: http://prometheus:9090
          isDefault: true
          editable: true

        - name: Loki
          access: proxy
          type: loki
          url: http://loki-gateway
          editable: true
          jsonData:
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: '"traceid"\s*:\s*"(.*?)"'
                name: TraceID
                url: '$${__value.raw}'

        - name: Tempo
          access: proxy
          uid: tempo
          type: tempo
          url: http://tempo.observability:3100
          editable: true
    

# opentelemetry-collector
# ======================================================================================================================
opentelemetry-collector:
  fullnameOverride: "otel-collector"
  enabled: true
  serviceAccount:
    create: false
    name: dev-140891-observability
    annotations:
      iam.gke.io/gcp-service-account: dev-140891-observability@paul-soladoye.iam.gserviceaccount.com
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    node_pool: dev-140891-sb-pool
#    sandbox.gke.io/runtime: gvisor
  tolerations:
#    - key: sandbox.gke.io/runtime
#      value: gvisor
#      effect: NoSchedule
  mode: deployment
  config:
    connectors:
      forward:
    processors: 
      memory_limiter:
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20
      resourcedetection:
        detectors: [ gcp ]
        timeout: 10s
        override: false
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      googlecloud:
        log:
          default_log_name: "otel-exporter"
            
      loki:
        endpoint: http://loki-gateway/loki/api/v1/push
      
      otlp/tempo:
        endpoint: tempo.observability:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
#          processors: [ memory_limiter, batch ]
          exporters: [ logging, otlp/tempo, googlecloud ]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging ]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
#          processors: [ memory_limiter, batch ]
          exporters: [ logging, loki, forward ]
        logs/gcp:
          receivers: [ forward ]
#          processors: [ memory_limiter, batch, resourcedetection ]
          processors: [ batch ]
          exporters: [ logging, googlecloud ]

      telemetry:
        logs:
          level: debug
        metrics:
          level: detailed
          address: 0.0.0.0:8888
  ports:
    otlp-http:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP

# tempo
# ======================================================================================================================
tempo:
  enabled: true
  fullnameOverride: tempo
  tempo:
    receivers:
      otlp:
        protocols:
          http:
          grpc:
#    storage:
#      trace:
#        backend: gcs
#        gcs:
#          bucket_name: tempo
    server:
      http_listen_port: 3100
    securityContext: {}
#      readOnlyRootFilesystem: true
#      allowPrivilegeEscalation: false
#      capabilities:
#        drop:
#          - ALL
#      seccompProfile:
#        type: RuntimeDefault
  serviceAccount:
    create: false
    name: dev-140891-observability
    annotations:
      iam.gke.io/gcp-service-account: dev-140891-observability@paul-soladoye.iam.gserviceaccount.com
  securityContext: {}
#    runAsUser: 65532
#    runAsGroup: 65532
#    fsGroup: 65532
#    runAsNonRoot: true
  nodeSelector:
    node_pool: dev-140891-sb-pool
#    sandbox.gke.io/runtime: gvisor
  tolerations:
#    - key: sandbox.gke.io/runtime
#      value: gvisor
#      effect: NoSchedule

# loki
# ======================================================================================================================
loki:
  enabled: true
  test:
    enabled: false
  serviceAccount:
    create: false
    name: dev-140891-observability
    annotations:
      iam.gke.io/gcp-service-account: dev-140891-observability@paul-soladoye.iam.gserviceaccount.com
  loki:
    nodeSelector:
      node_pool: dev-140891-sb-pool
#      sandbox.gke.io/runtime: gvisor
    tolerations:
#      - key: sandbox.gke.io/runtime
#        value: gvisor
#        effect: NoSchedule
    auth_enabled: false
  monitoring:
    lokiCanary:
      enabled: false
    dashboards:
      enabled: false
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
    rules:
      enabled: false

# prometheus
# ======================================================================================================================
prometheus:
  enabled: false
  alertmanager:
    enabled: false
  kube-state-metrics: 
    enabled: false
  prometheus-node-exporter: 
    enabled: false
  prometheus-pushgateway: 
    enabled: false
  serviceAccounts:
    server:
      create: false
      name: dev-140891-observability
      annotations:
        iam.gke.io/gcp-service-account: dev-140891-observability@paul-soladoye.iam.gserviceaccount.com
  server:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    nodeSelector:
      node_pool: dev-140891-sb-pool
#      sandbox.gke.io/runtime: gvisor
    tolerations:
#      - key: sandbox.gke.io/runtime
#        value: gvisor
#        effect: NoSchedule

test:
  enabled: false