{{- if .Values.webapi.ingress.enabled -}}
{{- if and .Values.webapi.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.webapi.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.webapi.ingress.annotations "kubernetes.io/ingress.class" .Values.webapi.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.webapi.name }}
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "observability-app.labels" . | nindent 4 }}
  {{- with .Values.webapi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.webapi.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "observability-app.fullname" . }}-api-service
                port:
                  number: {{ .Values.webapi.service.port }}
{{- end }}