apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.appNamespace }}
  name: {{ include "sample-app.fullname" . }}-config-map
data:
  LoggerConfig__Use: {{ .Values.loggerConfigUse }}
  OpenTelemetry__EnableConsoleExporter: "false"
  OpenTelemetry__HttpProtobuf: {{ .Values.otelCollectorEndpoint }}