version: "3.9"
services:

  # =============================================================================================================
  # Web API
  # =============================================================================================================
  web:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_LOG_LEVEL=debug
      - OTEL_SERVICE_NAME=observability_web_api
      - OpenTelemetry__ServiceName=observability_web_api
#      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/service-account.json #https://cloud.google.com/run/docs/testing/local#docker-with-gcp-access
#    volumes:
#      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/service-account.json:ro
    depends_on:
      - otel-collector

  # =============================================================================================================
  # Worker
  # =============================================================================================================
  worker:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - OTEL_LOG_LEVEL=debug
      - OTEL_SERVICE_NAME=observability_worker
      - OpenTelemetry__ServiceName=observability_worker
    working_dir: /app/worker
    entrypoint: [dotnet, worker.dll]
    depends_on:
      - otel-collector
  
  # =============================================================================================================
  # Loki
  # =============================================================================================================
  loki:
    image: grafana/loki:2.8.0
    ports: 
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    
  # =============================================================================================================
  # Promtail
  # =============================================================================================================
  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    
  # =============================================================================================================
  # Tempo
  # =============================================================================================================
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317"
      - "4318"
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
  # Generate fake traces...
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    environment:
      - ENDPOINT=otel-collector:4317
    restart: always
    depends_on:
      - otel-collector
  
  
  # =============================================================================================================
  # Grafana
  # =============================================================================================================
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  
  # =============================================================================================================
  # Open-telemetry Collector
  # =============================================================================================================
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/otel/key.json
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ${HOME}/Downloads/otel-exporter-sa.json:/etc/otel/key.json
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
#      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
        
  # =============================================================================================================
  # Prometheus
  # =============================================================================================================
  prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      ports:
        - "9090:9090"
      command: --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus_data: {}