version: "3.9"
services:

  # =============================================================================================================
  # Web API
  # =============================================================================================================
  web:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/service-account.json #https://cloud.google.com/run/docs/testing/local#docker-with-gcp-access
#    volumes:
#      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/service-account.json:ro
    depends_on:
      - otel-collector

  # =============================================================================================================
  # Worker
  # =============================================================================================================
  worker:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    entrypoint: [dotnet, worker.dll]
    depends_on:
      - otel-collector
  
  # =============================================================================================================
  # Loki
  # =============================================================================================================
  loki:
    image: grafana/loki:2.6.0
    ports: 
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    
  # =============================================================================================================
  # Promtail
  # =============================================================================================================
  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    
  # =============================================================================================================
  # Grafana
  # =============================================================================================================
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  
  # =============================================================================================================
  # Open-telemetry Collector
  # =============================================================================================================
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
        
  # =============================================================================================================
  # Prometheus
  # =============================================================================================================
#  prometheus: