version: "3.9"
services:

  # =============================================================================================================
  # Web API
  # =============================================================================================================
  web:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # =============================================================================================================
  # Worker
  # =============================================================================================================
  worker:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    entrypoint: [dotnet, worker.dll]