receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
  resourcedetection:
    detectors: [ gcp ]
    timeout: 10s
    override: false
        
exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  logging:
    loglevel: debug
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    
  prometheus:
    endpoint: 0.0.0.0:8889
      
extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679
    
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp/tempo ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ loki ]
  
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 0.0.0.0:8888