receivers:
  otlp:
    protocols:
      grpc:
  
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: [ "localhost:8888" ]

processors:
  batch:
    
exporters:
  otlp:
    endpoint: otelcol:4317

  logging:
    loglevel: debug
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
      
extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679
    
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, loki ]
  
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 0.0.0.0:8888