receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
  resourcedetection:
    detectors: [ gcp ]
    timeout: 10s
    
exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  logging:
    loglevel: debug
#    verbosity: detailed
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    
  prometheus:
    endpoint: 0.0.0.0:8889
    
  googlecloud:
    log:
      default_log_name: "opentelemetry.io/collector-exported-log"
      
extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679
    
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlp, googlecloud ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, prometheus, googlecloud ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, loki, googlecloud ]
  
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 0.0.0.0:8888